workflows:
  android-apk:
    name: Vyapari Android APK
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        PACKAGE_NAME: "com.vyapari.app"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build signed APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk