 workflows:
  android-release:
    name: Vyapari Android APK
    max_build_duration: 60
    environment:
      node: 18
      java: 17
      android_signing:
        - vyapari_keystore
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build SIGNED release APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
     
        
        

  

    
    
